name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'Tag Number'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: print input
      run: echo "Tag Number is  ${{ github.event.inputs.tag }}"
    - name: get list of release
      run: |
            curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.create_release }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/rohanbas95/Devops-Projects-AtoZ/releases
