name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'Tag Number'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: print input
      run: echo "Tag Number is  ${{ github.event.inputs.tag }}"
    - name: Group of log lines
      run: |
            echo "::group::My title 1"
            echo "Inside group wefiowejfwoeifjwefj"
            echo "::endgroup::"
            echo "::group::My title 2"
            echo "Inside group wqwqwqwqqwqwqqwqwqw"
            echo "::endgroup::"
