name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'Tag Number'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: print input
      run: echo "Tag Number is  ${{ github.event.inputs.tag }}"
    - name: get list of release
      run: |
            curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.create_release }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/rohanbas95/asurion_test1/releases
    - name: create release for asurion_test1
      run: |
            curl -X POST \ -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.create_release }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/rohanbas95/asurion_test1/releases -d '{"tag_name":"${{ github.event.inputs.tag }}","name":"${{ github.event.inputs.tag }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":true}'
    - name: create release for asurion_test2
      run: |
            curl -X POST \ -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.create_release }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/rohanbas95/asurion_test2/releases -d '{"tag_name":"${{ github.event.inputs.tag }}","name":"${{ github.event.inputs.tag }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":true}'
    - name: create release for asurion_test3
      run: |
            curl -X POST \ -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.create_release }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/rohanbas95/asurion_test3/releases -d '{"tag_name":"${{ github.event.inputs.tag }}","name":"${{ github.event.inputs.tag }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":true}'
