name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'Tag Number'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: print input
      run: echo "Tag Number is  ${{ github.event.inputs.tag }}"
    - name: Group of log lines
      run: |
            echo "::group::npx acdk diff"
            echo "Logs for npx acdk diff"
            echo "::endgroup::"
            echo "::group::npx acdk deploy"
            echo "npx acdk deploy"
            echo "::endgroup::"
